#!/usr/bin/env bash
# Battery statistics command for i3 Lemonbar

# Get battery percentage
i=0
while [ "$i" -lt 10 ]; do
    if [ -d /sys/class/power_supply/BAT${i} ]; then
        DIR='/sys/class/power_supply/BAT'$i
        break
    fi
    i=$((i+1))
done

CAPACITY=$(cat $DIR/capacity) # Charged percentage

# Get charging status
CHARGING="D"

if [[ `cat $DIR/status` == *"Charging"* ]]; then
  CHARGING="C"
fi
if [[ `cat $DIR/status` == *"Full"* ]]; then
  CHARGING="C"
fi

# Get power level status
STATUS="N"

if [[ $CAPACITY -ge 85 ]]; then
  STATUS="F";
elif [[ $CAPACITY -ge 30 ]]; then
  STATUS="G";
elif [[ $CAPACITY -lt 10 ]]; then
  STATUS="C"
fi

echo "BAT$CAPACITY $CHARGING $STATUS"
